version: "3.8"
    
services:
  db:
    image: mysql
    container_name: db_smart_doctrina
    command: --init-file /data/application/init.sql
    volumes:
      - db_data:/var/lib/mysql
      - ./dump_mysql/doctrina.sql:/data/application/init.sql
    restart: always
    environment: 
       MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    networks: 
       - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_smart_doctrina
    restart: always
    depends_on: 
       - db
    ports: 
        - 8000:80
    environment: 
      PMA_HOST : db       
    networks: 
       - dev     
  
  www:
        build: docker
        container_name: www_docker_symfony
        ports:
          - "8082:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev


volumes:
  db_data :

networks: 
   dev : 