<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDo0E6x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDo0E6x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDo0E6x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDo0E6x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDo0E6x\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDo0E6x',
    'container.build_id' => 'd29e516b',
    'container.build_time' => 1616230033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDo0E6x');
